# Cloud Build configuration for billing service
# This builds the Docker image and deploys it to Cloud Run

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/billing:$SHORT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/billing:latest'
      - '-f'
      - 'apps/billing/Dockerfile'
      - '.'

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/billing'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_ENV}-billing'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/billing:$SHORT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=9000'
      - '--set-env-vars=LOG_LEVEL=INFO'
      - '--update-secrets=STRIPE_SECRET_KEY=${_ENV}-stripe-secret-key:latest'
      - '--update-secrets=STRIPE_WEBHOOK_SECRET=${_ENV}-stripe-webhook-secret:latest'
      - '--update-secrets=ADMIN_API_URL=${_ENV}-admin-api-url:latest'
      - '--update-secrets=ADMIN_API_TOKEN=${_ENV}-admin-api-token:latest'
      - '--update-secrets=PORTAL_RETURN_URL=${_ENV}-portal-return-url:latest'

# Substitutions (can be overridden by trigger)
substitutions:
  _ENV: 'dev'
  _REGION: 'us-central1'
  _ARTIFACT_REGISTRY_REPO: 'dev-vexa-billing'

# Build timeout
timeout: '1200s'

# Store images in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/billing:$SHORT_SHA'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/billing:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

